// <auto-generated />
using System;
using FevCore.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FevCore.Infrastructure.Migrations
{
    [DbContext(typeof(FevCoreDbContext))]
    [Migration("20260925224010_AgregarIntegradores")]
    partial class AgregarIntegradores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FevCore.Domain.Documentos.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Consecutivo")
                        .HasColumnType("bigint");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntegradorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReferenciaExterna")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IntegradorId", "ReferenciaExterna")
                        .IsUnique()
                        .HasDatabaseName("ix_documentos_integrador_referencia");

                    b.HasIndex("Prefijo", "Consecutivo")
                        .IsUnique()
                        .HasDatabaseName("ix_documentos_prefijo_consecutivo");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("FevCore.Domain.Integradores.Integrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LlaveHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LlaveHash")
                        .IsUnique()
                        .HasDatabaseName("ix_integradores_llave_hash");

                    b.ToTable("integradores", (string)null);
                });

            modelBuilder.Entity("FevCore.Domain.Documentos.Documento", b =>
                {
                    b.OwnsMany("FevCore.Domain.Documentos.Linea", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("DocumentoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("BaseGravable")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<decimal>("Descuento")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<int>("Numero")
                                .HasColumnType("integer");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<Guid?>("ProductoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Total")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<string>("UnidadMedida")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.HasKey("DocumentoId", "Id");

                            b1.ToTable("lineas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DocumentoId");

                            b1.OwnsMany("FevCore.Domain.Documentos.ImpuestoLinea", "Impuestos", b2 =>
                                {
                                    b2.Property<Guid>("LineaDocumentoId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("LineaId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<decimal>("BaseGravable")
                                        .HasColumnType("numeric(18,6)");

                                    b2.Property<decimal>("Tarifa")
                                        .HasColumnType("numeric(8,4)");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.Property<decimal>("Valor")
                                        .HasColumnType("numeric(18,6)");

                                    b2.HasKey("LineaDocumentoId", "LineaId", "Id");

                                    b2.ToTable("impuestos_linea", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("LineaDocumentoId", "LineaId");
                                });

                            b1.Navigation("Impuestos");
                        });

                    b.OwnsOne("FevCore.Domain.Documentos.Totales", "Totales", b1 =>
                        {
                            b1.Property<Guid>("DocumentoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("TotalAPagar")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalAPagar");

                            b1.Property<decimal>("TotalBaseImponible")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalBaseImponible");

                            b1.Property<decimal>("TotalBruto")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalBruto");

                            b1.Property<decimal>("TotalDescuentos")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalDescuentos");

                            b1.Property<decimal>("TotalImpuestos")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalImpuestos");

                            b1.HasKey("DocumentoId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoId");
                        });

                    b.Navigation("Lineas");

                    b.Navigation("Totales")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
