// <auto-generated />
using System;
using FevCore.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FevCore.Infrastructure.Migrations
{
    [DbContext(typeof(FevCoreDbContext))]
    [Migration("20260928220311_AgregarNotasEHistorial")]
    partial class AgregarNotasEHistorial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FevCore.Domain.Adquirentes.Adquirente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("adquirentes", (string)null);
                });

            modelBuilder.Entity("FevCore.Domain.Documentos.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdquirenteId")
                        .HasColumnType("uuid");

                    b.Property<long>("Consecutivo")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("DocumentoReferenciadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntegradorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReferenciaExterna")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoReferenciadoId")
                        .HasDatabaseName("ix_documentos_referenciado");

                    b.HasIndex("IntegradorId", "ReferenciaExterna")
                        .IsUnique()
                        .HasDatabaseName("ix_documentos_integrador_referencia");

                    b.HasIndex("Prefijo", "Consecutivo")
                        .IsUnique()
                        .HasDatabaseName("ix_documentos_prefijo_consecutivo");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("FevCore.Domain.Emisores.Emisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("emisores", (string)null);
                });

            modelBuilder.Entity("FevCore.Domain.Integradores.Integrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LlaveHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LlaveHash")
                        .IsUnique()
                        .HasDatabaseName("ix_integradores_llave_hash");

                    b.ToTable("integradores", (string)null);
                });

            modelBuilder.Entity("FevCore.Domain.Numeracion.RangoNumeracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClaveTecnica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroAutorizacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("NumeroFinal")
                        .HasColumnType("bigint");

                    b.Property<long>("NumeroInicial")
                        .HasColumnType("bigint");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("UltimoAsignado")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Prefijo", "TipoDocumento")
                        .HasDatabaseName("ix_rangos_prefijo_tipo");

                    b.HasIndex("TipoDocumento", "VigenteDesde", "VigenteHasta")
                        .HasDatabaseName("ix_rangos_tipo_vigencia");

                    b.ToTable("rangos_numeracion", (string)null);
                });

            modelBuilder.Entity("FevCore.Domain.Productos.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasDatabaseName("ix_productos_codigo");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("FevCore.Domain.Adquirentes.Adquirente", b =>
                {
                    b.OwnsOne("FevCore.Domain.Comun.DatosTributarios", "Datos", b1 =>
                        {
                            b1.Property<Guid>("AdquirenteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Correo")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("DigitoVerificacion")
                                .HasMaxLength(1)
                                .HasColumnType("character varying(1)");

                            b1.Property<string>("Direccion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Identificacion")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("MunicipioCodigo")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RazonSocial")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Regimen")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Responsabilidades")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Telefono")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("TipoIdentificacion")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.HasKey("AdquirenteId");

                            b1.HasIndex("TipoIdentificacion", "Identificacion")
                                .HasDatabaseName("ix_adquirentes_identificacion");

                            b1.ToTable("adquirentes");

                            b1.WithOwner()
                                .HasForeignKey("AdquirenteId");
                        });

                    b.Navigation("Datos")
                        .IsRequired();
                });

            modelBuilder.Entity("FevCore.Domain.Documentos.Documento", b =>
                {
                    b.HasOne("FevCore.Domain.Documentos.Documento", null)
                        .WithMany()
                        .HasForeignKey("DocumentoReferenciadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("FevCore.Domain.Comun.DatosTributarios", "AdquirenteSnapshot", b1 =>
                        {
                            b1.Property<Guid>("DocumentoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Correo")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("DigitoVerificacion")
                                .HasMaxLength(1)
                                .HasColumnType("character varying(1)");

                            b1.Property<string>("Direccion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Identificacion")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("MunicipioCodigo")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RazonSocial")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Regimen")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Responsabilidades")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Telefono")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("TipoIdentificacion")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.HasKey("DocumentoId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoId");
                        });

                    b.OwnsOne("FevCore.Domain.Comun.DatosTributarios", "EmisorSnapshot", b1 =>
                        {
                            b1.Property<Guid>("DocumentoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Correo")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("DigitoVerificacion")
                                .HasMaxLength(1)
                                .HasColumnType("character varying(1)");

                            b1.Property<string>("Direccion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Identificacion")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("MunicipioCodigo")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RazonSocial")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Regimen")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Responsabilidades")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Telefono")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("TipoIdentificacion")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.HasKey("DocumentoId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoId");
                        });

                    b.OwnsMany("FevCore.Domain.Documentos.Linea", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("DocumentoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("BaseGravable")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<decimal>("Descuento")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<int>("Numero")
                                .HasColumnType("integer");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<Guid?>("ProductoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Total")
                                .HasColumnType("numeric(18,6)");

                            b1.Property<string>("UnidadMedida")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.HasKey("DocumentoId", "Id");

                            b1.ToTable("lineas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DocumentoId");

                            b1.OwnsMany("FevCore.Domain.Documentos.ImpuestoLinea", "Impuestos", b2 =>
                                {
                                    b2.Property<Guid>("LineaDocumentoId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("LineaId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<decimal>("BaseGravable")
                                        .HasColumnType("numeric(18,6)");

                                    b2.Property<decimal>("Tarifa")
                                        .HasColumnType("numeric(8,4)");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.Property<decimal>("Valor")
                                        .HasColumnType("numeric(18,6)");

                                    b2.HasKey("LineaDocumentoId", "LineaId", "Id");

                                    b2.ToTable("impuestos_linea", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("LineaDocumentoId", "LineaId");
                                });

                            b1.Navigation("Impuestos");
                        });

                    b.OwnsOne("FevCore.Domain.Documentos.Totales", "Totales", b1 =>
                        {
                            b1.Property<Guid>("DocumentoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("TotalAPagar")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalAPagar");

                            b1.Property<decimal>("TotalBaseImponible")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalBaseImponible");

                            b1.Property<decimal>("TotalBruto")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalBruto");

                            b1.Property<decimal>("TotalDescuentos")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalDescuentos");

                            b1.Property<decimal>("TotalImpuestos")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("TotalImpuestos");

                            b1.HasKey("DocumentoId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoId");
                        });

                    b.OwnsMany("FevCore.Domain.Documentos.TransicionEstado", "Transiciones", b1 =>
                        {
                            b1.Property<Guid>("DocumentoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Secuencia")
                                .HasColumnType("integer");

                            b1.Property<string>("Detalle")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("EstadoAnterior")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("EstadoNuevo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Motivo")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<DateTimeOffset>("OcurridaEn")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("DocumentoId", "Secuencia");

                            b1.ToTable("transiciones_estado", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DocumentoId");
                        });

                    b.Navigation("AdquirenteSnapshot")
                        .IsRequired();

                    b.Navigation("EmisorSnapshot")
                        .IsRequired();

                    b.Navigation("Lineas");

                    b.Navigation("Totales")
                        .IsRequired();

                    b.Navigation("Transiciones");
                });

            modelBuilder.Entity("FevCore.Domain.Emisores.Emisor", b =>
                {
                    b.OwnsOne("FevCore.Domain.Comun.DatosTributarios", "Datos", b1 =>
                        {
                            b1.Property<Guid>("EmisorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Correo")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("DigitoVerificacion")
                                .HasMaxLength(1)
                                .HasColumnType("character varying(1)");

                            b1.Property<string>("Direccion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Identificacion")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("MunicipioCodigo")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RazonSocial")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Regimen")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Responsabilidades")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Telefono")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("TipoIdentificacion")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.HasKey("EmisorId");

                            b1.ToTable("emisores");

                            b1.WithOwner()
                                .HasForeignKey("EmisorId");
                        });

                    b.Navigation("Datos")
                        .IsRequired();
                });

            modelBuilder.Entity("FevCore.Domain.Productos.Producto", b =>
                {
                    b.OwnsMany("FevCore.Domain.Documentos.EspecificacionImpuesto", "Impuestos", b1 =>
                        {
                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Tarifa")
                                .HasColumnType("numeric(8,4)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("ProductoId", "Id");

                            b1.ToTable("impuestos_producto", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.Navigation("Impuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
